# Generated by Django 5.0.1 on 2024-01-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('area_name', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
